"use strict";
const assert = require("node:assert/strict");
const path = require("node:path");
const {pathToFileURL} = require("node:url");
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || "playwright");
(async () => {
    const browser = await chromium.launch({headless: true});
    const errors = [];
    const page = await browser.newPage({viewport: {width: 1560, height: 1100}, deviceScaleFactor: 2});
    page.on("pageerror", error => errors.push(error.message));
    const url = process.env.RECONFIGURABLE_URL || pathToFileURL(path.resolve(__dirname, "../RECONFIGURABLE_COMPUTE.html")).href;
    await page.goto(url);
    await page.waitForFunction(() => window.ReconfigurableCompute);
    assert.equal(await page.locator("h1").textContent(), "Reconfigurable compute");
    assert.equal(await page.locator("details[open]").count(), 0);
    assert.equal(await page.locator("canvas").count(), 2);
    assert.equal(await page.locator("#rc-decode").getAttribute("aria-pressed"), "true");
    assert.match(await page.locator("#rc-takeaway").textContent(), /1\.74/);
    assert.match(await page.locator("#rc-performance-rows").textContent(), /879,234/);
    assert.match(await page.locator("#rc-performance-rows").textContent(), /506,178/);
    const dims = await page.locator("canvas").evaluateAll(nodes => nodes.map(c => [c.width, c.height]));
    assert.ok(dims.every(([w, h]) => w >= 1200 && h >= 1184));
    const canvas = page.locator("#rc-canvas-reuse");
    const box = await canvas.boundingBox();
    await canvas.click({position: {x: (64 + 2 * 28 + 12) / 600 * box.width, y: (88 + 4 * 28 + 12) / 592 * box.height}});
    assert.match(await page.locator("#rc-pe-title").textContent(), /PE \(4, 2\)/);
    assert.match(await page.locator("#rc-pe-stream").textContent(), /does not exist/);
    await canvas.focus(); await page.keyboard.press("ArrowLeft");
    assert.match(await page.locator("#rc-pe-title").textContent(), /PE \(4, 1\)/);
    assert.equal(await page.locator("#rc-weight-slots > div").count(), 16);
    await page.locator("#rc-prefill").click();
    assert.match(await page.locator("#rc-takeaway").textContent(), /1\.05/);
    assert.equal(await page.locator("#rc-card-reuse").getAttribute("data-selected"), "true");
    await page.locator("#rc-scrub").fill("63");
    assert.match(await page.locator("#rc-pe-owner").textContent(), /O\[12, 20\]/);
    await page.locator("#rc-reset").click();
    await page.locator("#rc-step").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).step, 1);
    await page.locator("#rc-play").click();
    await page.waitForFunction(() => ReconfigurableCompute.inspect().step > 2);
    await page.locator("#rc-play").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).playing, false);
    await page.locator("#rc-decode").click();
    await page.locator("#rc-inspect-policy").selectOption("outputs");
    await page.locator("#rc-inspect-col").selectOption("0");
    await page.locator("#rc-inspect-row").selectOption("4");
    await page.locator("#theme-toggle").click();
    await page.screenshot({path: "/tmp/reconfigurable-compute-desktop.png", fullPage: true, animations: "disabled"});
    await page.locator("#theme-toggle").click();
    await page.screenshot({path: "/tmp/reconfigurable-compute-light.png", fullPage: true, animations: "disabled"});
    for (const width of [1280, 768, 390]) {
        await page.setViewportSize({width, height: 1000});
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `No horizontal page overflow at ${width}px`);
        await page.locator("#rc-prefill").click();
        await page.locator("#rc-decode").click();
    }
    await page.screenshot({path: "/tmp/reconfigurable-compute-mobile.png", fullPage: true, animations: "disabled"});
    await page.emulateMedia({reducedMotion: "reduce"});
    await page.reload();
    await page.waitForFunction(() => window.ReconfigurableCompute);
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).playing, false);
    await page.locator("#rc-step").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).step, 16);
    assert.deepEqual(errors, []);
    await browser.close();
    console.log("PASS: both phases, playback, PE hit testing, keyboard, high-DPI canvas, themes, mobile and reduced motion.");
})().catch(error => { console.error(error); process.exitCode = 1; });
