"use strict";
const assert = require("node:assert/strict");
const path = require("node:path");
const {pathToFileURL} = require("node:url");
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || "playwright");
(async () => {
    const browser = await chromium.launch({headless: true});
    const errors = [];
    const page = await browser.newPage({viewport: {width: 1560, height: 1100}, deviceScaleFactor: 2});
    page.on("pageerror", error => errors.push(error.message));
    const url = process.env.RECONFIGURABLE_URL || pathToFileURL(path.resolve(__dirname, "../RECONFIGURABLE_COMPUTE.html")).href;
    await page.goto(url);
    await page.waitForFunction(() => window.ReconfigurableCompute);
    assert.match(await page.locator("h1").textContent(), /Switch the dataflow/);
    assert.equal(await page.locator("details[open]").count(), 0);
    assert.equal(await page.locator("canvas").count(), 2);
    assert.equal(await page.locator("#rc-decode").getAttribute("aria-pressed"), "true");
    assert.equal(await page.locator("#rc-gain").textContent(), "42.4%");
    assert.match(await page.locator("#rc-race-saved").textContent(), /373,056.*1\.74/);
    assert.match(await page.locator("#rc-cause-chain").textContent(), /64 → 128/);
    assert.ok((await page.locator("#rc-result").boundingBox()).y < 650, "Performance result leads the page");
    await page.locator("#rc-race-scrub").fill("506178");
    assert.equal(await page.locator("#rc-race-status-adaptive").textContent(), "Finished");
    assert.match(await page.locator("#rc-race-status-fixed").textContent(), /373,056 cycles left/);
    await page.locator("#rc-race-scrub").fill("0");
    assert.notEqual(await page.locator("#rc-race-status-adaptive").textContent(), "Finished");
    await page.locator("#rc-race-play").click();
    await page.waitForFunction(() => ReconfigurableCompute.inspect().cycle > 0);
    await page.locator("#rc-race-play").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).racing, false);
    assert.match(await page.locator("#rc-performance-rows").textContent(), /879,234/);
    assert.match(await page.locator("#rc-performance-rows").textContent(), /506,178/);
    const dims = await page.locator("canvas").evaluateAll(nodes => nodes.map(c => [c.width, c.height]));
    assert.ok(dims.every(([w, h]) => w >= 1200 && h >= 1184));
    const canvas = page.locator("#rc-canvas-fixed");
    const box = await canvas.boundingBox();
    await canvas.click({position: {x: (64 + 2 * 28 + 12) / 600 * box.width, y: (88 + 4 * 28 + 12) / 592 * box.height}});
    assert.match(await page.locator("#rc-pe-title").textContent(), /PE \(4, 2\)/);
    assert.match(await page.locator("#rc-pe-stream").textContent(), /does not exist/);
    await canvas.focus(); await page.keyboard.press("ArrowLeft");
    assert.match(await page.locator("#rc-pe-title").textContent(), /PE \(4, 1\)/);
    assert.equal(await page.locator("#rc-weight-slots > div").count(), 16);
    await page.locator("#rc-prefill").click();
    assert.equal(await page.locator("#rc-gain").textContent(), "Same");
    assert.equal(await page.locator("#rc-name-fixed").textContent(), await page.locator("#rc-name-adaptive").textContent());
    await page.locator("#rc-baseline").selectOption("outputs");
    assert.equal(await page.locator("#rc-gain").textContent(), "4.7%");
    assert.match(await page.locator("#rc-race-saved").textContent(), /1,572,864.*1\.05/);
    await page.locator("#rc-baseline").selectOption("reuse");
    await page.locator("#rc-scrub").fill("63");
    assert.match(await page.locator("#rc-pe-owner").textContent(), /O\[12, 20\]/);
    await page.locator("#rc-reset").click();
    await page.locator("#rc-step").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).step, 1);
    await page.locator("#rc-play").click();
    await page.waitForFunction(() => ReconfigurableCompute.inspect().step > 2);
    await page.locator("#rc-play").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).playing, false);
    await page.locator("#rc-decode").click();
    await page.locator("#rc-inspect-panel").selectOption("adaptive");
    await page.locator("#rc-inspect-col").selectOption("0");
    await page.locator("#rc-inspect-row").selectOption("4");
    await page.locator("#rc-baseline").selectOption("outputs");
    assert.equal(await page.locator("#rc-gain").textContent(), "Same");
    await page.locator("#rc-baseline").selectOption("reuse");
    await page.locator("#rc-story").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).phase, "prefill");
    assert.equal(await page.locator("#rc-gain").textContent(), "Same");
    await page.waitForFunction(() => ReconfigurableCompute.inspect().phase === "decode" && ReconfigurableCompute.inspect().racing);
    assert.equal(await page.locator("#rc-gain").textContent(), "42.4%");
    await page.locator("#rc-prefill").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).racing, false);
    await page.locator("#rc-story").click();
    await page.locator("#rc-decode").click();
    await page.waitForTimeout(2600);
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).racing, false, "Manual phase choice cancels guided replay");
    await page.locator("#rc-play").click();
    await page.locator("#rc-race-play").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).playing, false, "Two clocks never play together");
    await page.locator("#rc-decode").click();
    await page.locator("#rc-inspector summary").click();
    await page.evaluate(() => window.scrollTo(0, 0));
    await page.locator("#theme-toggle").click();
    await page.screenshot({path: "/tmp/reconfigurable-switching-desktop.png", fullPage: true, animations: "disabled"});
    await page.locator("#theme-toggle").click();
    await page.screenshot({path: "/tmp/reconfigurable-switching-light.png", fullPage: true, animations: "disabled"});
    for (const width of [1280, 768, 390]) {
        await page.setViewportSize({width, height: 1000});
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `No horizontal page overflow at ${width}px`);
        await page.locator("#rc-prefill").click();
        await page.locator("#rc-decode").click();
    }
    await page.screenshot({path: "/tmp/reconfigurable-switching-mobile.png", fullPage: true, animations: "disabled"});
    await page.emulateMedia({reducedMotion: "reduce"});
    await page.reload();
    await page.waitForFunction(() => window.ReconfigurableCompute);
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).playing, false);
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).racing, false);
    await page.locator("#rc-step").click();
    assert.equal((await page.evaluate(() => ReconfigurableCompute.inspect())).step, 16);
    assert.deepEqual(errors, []);
    await browser.close();
    console.log("PASS: performance lead, fixed baselines, phase switching, finish-time race, clock isolation, PE inspection, themes, mobile and reduced motion.");
})().catch(error => { console.error(error); process.exitCode = 1; });
