// Generated by tools/build_reconfigurable_compute.py.
(function(root){
"use strict";
const data={
  "hardware": {
    "AH": 16,
    "AW": 16,
    "D_OB": 64,
    "D_StaB": 128,
    "D_StrB": 64
  },
  "policies": {
    "outputs": {
      "Kt": 32,
      "Mt": 16,
      "Nt": 64,
      "name": "B \u00b7 Cover more outputs",
      "replicas": 2
    },
    "reuse": {
      "Kt": 32,
      "Mt": 32,
      "Nt": 32,
      "name": "A \u00b7 Reuse across tokens",
      "replicas": 4
    }
  },
  "provenance": {
    "animation": "First M/N/K tile only. Row-skewed teaching steps omit preload and instruction gaps; distinct from predicted program cycles.",
    "baseline": "Two fixed spatial mapping policies. M tile clips to workload; legal input layout may adapt to M. Same hardware, K tile and W/O orders. Neither is every possible fixed mapping.",
    "costModel": "serialized_minisa_v2",
    "model": "Qwen/Qwen3-0.6B",
    "modelRevision": "c1899de289a04d12100db370d81485cdf75e47ca",
    "scope": "One complete q_proj invocation per phase; batch 1; FP16 inputs/weights, FP32 accumulation.",
    "sourceCommit": "28748363ea8e07f8c678fb9f11969465ae8f174c",
    "sourceSha256": {
      "compiler/ACT/launch_cost_model.py": "d9a9fd925b351bcd9e66c2e1aa68d723463fbaa64699221ee97b7f8a0132a803",
      "minisa/config.py": "7a96ed50e8c0bf20fe4858c52c6e67d86b401920272af68a3f96c67a53039901",
      "minisa/isa.py": "ca97e689832f35de459b5979300e6f7fe25b5acfbe76d85b6d1dc249c880ff31",
      "minisa/layout.py": "c4f9cd7da4fc900dbab88a942a50ec690f2a6e2727adffcd8e5f84ffe7be14fe",
      "minisa/schedule_cost.py": "0f7a8fcf7043f1f08cf3197bd65bb2bde6afa62d18bf9e04c5a62963af5aee43",
      "minisa/search.py": "f70e7dff823e36b0bbcb9cdabd07f090c218154c904a103ee49b4e80d59246f3",
      "tb/statistics/qwen3_0p6b_fp16_manifest.json": "edbc6a9b8e1cef07116120228bb073bf4b190510e7340db5890a97ba1e0966f6"
    },
    "timing": "Serialized MINISA prediction including loads, PE preload, stream, gaps/drain, dispatch and stores. Operands already packed; excludes layout conversion, external stalls, non-GEMM work and host launch. No new RTL measurement."
  },
  "records": {
    "decode": {
      "outputs": {
        "EM": {
          "G_c": 4,
          "G_r": 8,
          "c_0": 0,
          "r_0": 0,
          "s_c": 16,
          "s_r": 1
        },
        "ES": {
          "T": 1,
          "dataflow": 1,
          "m_0": 0,
          "s_m": 2,
          "vn_size": 15
        },
        "cost": {
          "bytes_in": 65536,
          "bytes_out": 4096,
          "bytes_w": 4194304,
          "conversion_cycles": 0,
          "cost_model": "serialized_minisa_v2",
          "dispatch_cycles": 10338,
          "drain_cycles": 41984,
          "execution_cycles": 337920,
          "gap_cycles": 0,
          "instruction_bits": 166368,
          "instruction_bytes": 20796,
          "instruction_count": 6208,
          "instruction_stall_cycles": 1,
          "instruction_words": 5199,
          "load_in_cycles": 20480,
          "load_w_cycles": 135168,
          "mapping_count": 1024,
          "prime_cycles": 1024,
          "startup_cycles": 1,
          "store_cycles": 2272,
          "stream_cycles": 16384,
          "total_cycles": 506178,
          "weight_preload_cycles": 278528
        },
        "mappedPEs": 128,
        "orders": {
          "I": 0,
          "O": 0,
          "W": 2
        },
        "shape": {
          "K": 1024,
          "M": 1,
          "N": 2048
        },
        "tile": {
          "K": 32,
          "M": 1,
          "N": 64
        },
        "verifiedTileMacs": 2048
      },
      "reuse": {
        "EM": {
          "G_c": 2,
          "G_r": 8,
          "c_0": 0,
          "r_0": 0,
          "s_c": 16,
          "s_r": 1
        },
        "ES": {
          "T": 1,
          "dataflow": 1,
          "m_0": 0,
          "s_m": 4,
          "vn_size": 15
        },
        "cost": {
          "bytes_in": 131072,
          "bytes_out": 4096,
          "bytes_w": 4194304,
          "conversion_cycles": 0,
          "cost_model": "serialized_minisa_v2",
          "dispatch_cycles": 20674,
          "drain_cycles": 83968,
          "execution_cycles": 675840,
          "gap_cycles": 0,
          "instruction_bits": 332736,
          "instruction_bytes": 41592,
          "instruction_count": 12416,
          "instruction_stall_cycles": 1,
          "instruction_words": 10398,
          "load_in_cycles": 40960,
          "load_w_cycles": 139264,
          "mapping_count": 2048,
          "prime_cycles": 2048,
          "startup_cycles": 1,
          "store_cycles": 2496,
          "stream_cycles": 32768,
          "total_cycles": 879234,
          "weight_preload_cycles": 557056
        },
        "mappedPEs": 64,
        "orders": {
          "I": 0,
          "O": 0,
          "W": 2
        },
        "shape": {
          "K": 1024,
          "M": 1,
          "N": 2048
        },
        "tile": {
          "K": 32,
          "M": 1,
          "N": 32
        },
        "verifiedTileMacs": 1024
      }
    },
    "prefill": {
      "outputs": {
        "EM": {
          "G_c": 4,
          "G_r": 8,
          "c_0": 0,
          "r_0": 0,
          "s_c": 16,
          "s_r": 1
        },
        "ES": {
          "T": 8,
          "dataflow": 1,
          "m_0": 0,
          "s_m": 2,
          "vn_size": 15
        },
        "cost": {
          "bytes_in": 50331648,
          "bytes_out": 3145728,
          "bytes_w": 201326592,
          "conversion_cycles": 0,
          "cost_model": "serialized_minisa_v2",
          "dispatch_cycles": 496130,
          "drain_cycles": 2015232,
          "execution_cycles": 23101440,
          "gap_cycles": 1376256,
          "instruction_bits": 7985664,
          "instruction_bytes": 998208,
          "instruction_count": 297984,
          "instruction_stall_cycles": 1,
          "instruction_words": 249552,
          "load_in_cycles": 1769472,
          "load_w_cycles": 6488064,
          "mapping_count": 49152,
          "prime_cycles": 49152,
          "startup_cycles": 1,
          "store_cycles": 1583616,
          "stream_cycles": 6291456,
          "total_cycles": 33438722,
          "weight_preload_cycles": 13369344
        },
        "mappedPEs": 256,
        "orders": {
          "I": 2,
          "O": 0,
          "W": 2
        },
        "shape": {
          "K": 1024,
          "M": 768,
          "N": 2048
        },
        "tile": {
          "K": 32,
          "M": 16,
          "N": 64
        },
        "verifiedTileMacs": 32768
      },
      "reuse": {
        "EM": {
          "G_c": 2,
          "G_r": 8,
          "c_0": 0,
          "r_0": 0,
          "s_c": 16,
          "s_r": 1
        },
        "ES": {
          "T": 8,
          "dataflow": 1,
          "m_0": 0,
          "s_m": 4,
          "vn_size": 15
        },
        "cost": {
          "bytes_in": 100663296,
          "bytes_out": 3145728,
          "bytes_w": 100663296,
          "conversion_cycles": 0,
          "cost_model": "serialized_minisa_v2",
          "dispatch_cycles": 496130,
          "drain_cycles": 2015232,
          "execution_cycles": 23101440,
          "gap_cycles": 1376256,
          "instruction_bits": 7985664,
          "instruction_bytes": 998208,
          "instruction_count": 297984,
          "instruction_stall_cycles": 1,
          "instruction_words": 249552,
          "load_in_cycles": 3342336,
          "load_w_cycles": 3342336,
          "mapping_count": 49152,
          "prime_cycles": 49152,
          "startup_cycles": 1,
          "store_cycles": 1583616,
          "stream_cycles": 6291456,
          "total_cycles": 31865858,
          "weight_preload_cycles": 13369344
        },
        "mappedPEs": 256,
        "orders": {
          "I": 2,
          "O": 0,
          "W": 2
        },
        "shape": {
          "K": 1024,
          "M": 768,
          "N": 2048
        },
        "tile": {
          "K": 32,
          "M": 32,
          "N": 32
        },
        "verifiedTileMacs": 32768
      }
    }
  },
  "schema": 1,
  "weightsPerPE": 16
};
if(typeof module==="object"&&module.exports)module.exports=data;
root.ReconfigurableComputeData=data;
})(typeof globalThis!=="undefined"?globalThis:this);
