#!/usr/bin/env python3
"""Export verified routing-only examples from the maintained BIRRD+ compiler."""
import argparse
import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def build(repo):
    compiler = repo / 'compiler/BIRRD_Config_Gen'
    sys.path.insert(0, str(compiler))
    from birrd_plus_router import BirrdPlusRouter
    from birrd_plus_inst import birrd_plus_from_inst, _get_wiring
    router = BirrdPlusRouter(16)
    cases = []
    orders = [
        ('rows', 'Row-major', list(range(16))),
        ('columns', 'Column-major', [r * 4 + c for c in range(4) for r in range(4)]),
        ('tiles', '2×2 tiles', [(br + r) * 4 + bc + c for br in (0, 2) for bc in (0, 2) for r in (0, 1) for c in (0, 1)]),
    ]
    wiring = _get_wiring(16)
    for key, label, target in orders:
        inst = router.route_permutation(target)
        assert list(birrd_plus_from_inst(list(range(16)), inst, 16)) == target
        commands = inst[:, ::2].tolist()
        assert all(cmd in (0, 3) for stage in commands for cmd in stage)
        lanes = list(range(16))
        states = [lanes]
        for connections, commands_at_stage in zip(wiring, commands):
            next_lanes = []
            for (lo, hi), cmd in zip(connections, commands_at_stage):
                next_lanes.extend([lanes[hi], lanes[lo]] if cmd == 3 else [lanes[lo], lanes[hi]])
            states.append(next_lanes)
            lanes = next_lanes
        assert lanes == target
        cases.append(dict(id=key, label=label, target=target, commands=commands, states=states))
    files = ['compiler/BIRRD_Config_Gen/birrd_plus_inst.py', 'compiler/BIRRD_Config_Gen/birrd_plus_router.py']
    data = dict(ports=16, stages=8, wiring=wiring, cases=cases,
                sources={name: hashlib.sha256((repo / name).read_bytes()).hexdigest() for name in files})
    return '/* Generated by tools/build_reconfigurable_layout.py. */\n' + \
        '(function(root){const data=' + json.dumps(data, separators=(',', ':')) + \
        ';if(typeof module==="object"&&module.exports)module.exports=data;else root.ReconfigurableLayoutData=data;})(globalThis);\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--repo', type=Path, required=True, help='FEATHER_GEMM checkout')
    parser.add_argument('--out', type=Path, default=ROOT / 'script/reconfigurable_layout_data.js')
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = build(args.repo)
    if args.check:
        if not args.out.exists() or args.out.read_text() != result:
            parser.exit(1, 'Layout examples are stale.\n')
        print('Verified: three compiler-routed layouts are current.')
    else:
        args.out.write_text(result)
        print('Wrote', args.out)


if __name__ == '__main__':
    main()
